trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'pharmacybackend2026'
  imageRepository: 'pharmacy-backend'
  imageTag: '$(Build.BuildId)'
  appName: 'pharmacy-backend-arun'
  resourceGroup: 'vms-group'

steps:

- checkout: self

# Build Spring Boot
- task: Maven@4
  displayName: 'Build Spring Boot'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package -DskipTests'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'

# Login to Azure, build image, push to ACR
- task: AzureCLI@2
  displayName: 'Build and Push Docker Image'
  inputs:
    azureSubscription: 'azure-rm-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(acrName)

      docker build -t $(acrName).azurecr.io/$(imageRepository):$(imageTag) .
      docker tag $(acrName).azurecr.io/$(imageRepository):$(imageTag) \
                 $(acrName).azurecr.io/$(imageRepository):latest

      docker push $(acrName).azurecr.io/$(imageRepository):$(imageTag)
      docker push $(acrName).azurecr.io/$(imageRepository):latest

# Configure App Service to use the new image
- task: AzureCLI@2
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'azure-rm-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az webapp config container set \
        --resource-group $(resourceGroup) \
        --name $(appName) \
        --container-image-name $(acrName).azurecr.io/$(imageRepository):$(imageTag)

      az webapp restart \
        --resource-group $(resourceGroup) \
        --name $(appName)
